In [1]:
import torch
import numpy as np
from torch.utils.data import DataLoader
import os, sys
import seaborn as sns
import matplotlib.pyplot as plt

currentdir = os.path.dirname(os.path.abspath(''))
parentdir = os.path.dirname(currentdir)
grandparentdir = os.path.dirname(parentdir)
sys.path.append(grandparentdir)

In [2]:
from res.process_data.dataset import tensor_dataset
from res.fnn.training import training_bce
import res.process_data.process_output as pro_out
import res.fnn.functions as func
import res.process_data.dire_and_coor as dc
import res.process_data.n_n_distance as nndistance
from res.process_data.dataset import tensor_dataset

/Users/dengnaicheng/Developer/intro_GANs/gansForPolymer/Naicheng/res/fnn


## single node
### check the target output

## input random walk

In [3]:
coor_input = np.load('../../data/random/16monos/coordinates.npy')
input_distance = nndistance.n_n_distance(coor_input)
print(input_distance)
print(input_distance ** 2)

3.8775610891383776
15.035480000000002


In [4]:
target = {}
for i in range(1, 21):
    target[f'epoch{i * 100}'] = {"backward": 0,
                                "forward": 0,
                                "left": 0,
                                "right": 0}
    generator = model.GeneratorNet()
    checkpoint = torch.load(f'random_models/three_layers/model_gan_{i * 100}.pth.tar')
    generator.load_state_dict(checkpoint['gen_state_dict'])
    noise = func.get_noise(10000, 8)
    output = generator(noise).data.numpy().reshape(150000)
    # sns.histplot(output)
    # plt.show()
    for j in output:
        if j < 0.1:
            target[f'epoch{i * 100}']['backward'] += 1
        elif 0.2 < j < 0.3:
            target[f'epoch{i * 100}']['right'] += 1
        elif 0.4 < j < 0.5:
            target[f'epoch{i * 100}']['forward'] += 1
        elif 0.7 < j < 0.8:
            target[f'epoch{i * 100}']['left'] += 1

NameError: name 'model' is not defined

In [5]:
a = []
b = []
c = []
d = []
for i in range(1, 21, 3):
    a.append(target[f'epoch{i * 100}']['backward'])
    b.append(target[f'epoch{i * 100}']['forward'])
    c.append(target[f'epoch{i * 100}']['left'])
    d.append(target[f'epoch{i * 100}']['right'])
plt.plot(a, label='backward')
plt.plot(b, label ='forward')
plt.plot(c, label = 'left')
plt.plot(d, label = 'right')
plt.legend()

KeyError: 'epoch400'

In [6]:
## check the n to n distance

In [4]:
import single_node as model
i = 20
generator = model.GeneratorNet()
checkpoint = torch.load(f'random_models/single_node/model_gan_{i * 100}.pth.tar')
generator.load_state_dict(checkpoint['gen_state_dict'])
noise = func.get_noise(10000, 8)
output = generator(noise).data.numpy()

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


check single node properties
1. check the parameters

In [10]:
for i in range(20):
    # noise_single = func.get_noise(1, 8)
    noise_single = func.get_noise(1,8)
    print(noise_single)
    real_output = generator(noise_single)
    print('---')

tensor([[0.2500, 0.0000, 0.2500, 0.0000, 0.5000, 0.2500, 0.0000, 0.7500]])
[[0.]]
---
tensor([[0.5000, 0.7500, 0.5000, 0.5000, 0.2500, 0.7500, 0.0000, 0.0000]])
[[0.]]
---
tensor([[0.5000, 0.5000, 0.5000, 0.7500, 0.0000, 0.7500, 0.0000, 0.0000]])
[[0.]]
---
tensor([[0.7500, 0.7500, 0.0000, 0.0000, 0.5000, 0.2500, 0.5000, 0.5000]])
[[0.]]
---
tensor([[0.5000, 0.7500, 0.5000, 0.2500, 0.7500, 0.0000, 0.7500, 0.0000]])
[[0.]]
---
tensor([[0.7500, 0.2500, 0.5000, 0.2500, 0.7500, 0.0000, 0.7500, 0.0000]])
[[0.]]
---
tensor([[0.0000, 0.7500, 0.5000, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000]])
[[0.]]
---
tensor([[0.7500, 0.5000, 0.5000, 0.2500, 0.0000, 0.5000, 0.5000, 0.2500]])
[[0.]]
---
tensor([[0.5000, 0.0000, 0.0000, 0.5000, 0.5000, 0.2500, 0.5000, 0.7500]])
[[0.]]
---
tensor([[0.0000, 0.0000, 0.5000, 0.5000, 0.7500, 0.2500, 0.2500, 0.0000]])
[[0.]]
---
tensor([[0.7500, 0.0000, 0.7500, 0.0000, 0.7500, 0.0000, 0.0000, 0.2500]])
[[0.]]
---
tensor([[0.0000, 0.7500, 0.2500, 0.5000, 0.7500, 0.500

In [12]:
a = []
for count, item  in enumerate(generator.parameters()):
    print(item)
    a.append(item.data.numpy())
    print(count)

Parameter containing:
tensor([[ 0.0027, -0.0060, -0.0034, -0.0062,  0.0100,  0.0066,  0.0059,  0.0081]],
       requires_grad=True)
0
Parameter containing:
tensor([-0.1084], requires_grad=True)
1
Parameter containing:
tensor([[-8.5719e+00],
        [-2.5396e+00],
        [-2.6911e-01],
        [-9.4946e-01],
        [-6.4407e-02],
        [-3.7138e-01],
        [ 5.2769e-02],
        [ 4.4616e-01],
        [-3.2238e-01],
        [ 4.0677e-01],
        [-1.2645e+00],
        [ 1.2883e-02],
        [-6.4543e-01],
        [-5.4203e-03],
        [ 1.4449e+00]], requires_grad=True)
2
Parameter containing:
tensor([-15.2514,   5.5576,  -0.3495,  -2.9737,  -1.0758,   0.9719,  -3.8360,
         -3.4223,   0.8375,   0.8938,   1.0845,   0.8597,  -3.8776,   0.7691,
         -6.6384], requires_grad=True)
3


what ever the input is, the output is always zero
so zero * everything is zero


In [14]:
first_weight = np.copy(a[0])
first_bias = np.copy(a[1])

In [15]:
np.shape(first_weight)


(1, 8)

In [18]:
noise = func.get_noise(1,8)

In [21]:
np.dot(noise_single, first_weight.transpose()) + first_bias

array([[-0.09733726]], dtype=float32)