In [12]:
import torch
import model as model
import numpy as np

In [4]:
import sys, os
currentdir = os.path.dirname(os.path.abspath(''))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)
print(parentdir)

/Users/dengnaicheng/Developer/intro_GANs/gansForPolymer/Naicheng


In [59]:
import res.fnn.functions as func
from res.process_data.dataset import tensor_dataset
from res.fnn.training import training_bce
import res.process_data.process_output as pro_out
import res.process_data.slice_output as so
import res.process_data.dire_and_coor as dc

In [92]:
# check the un-trained model
generator = model.GeneratorNet()
noise = func.get_noise(1000, 8)
output = generator(noise).data.numpy()
directions = np.round(so.slice_direction(output) * 4) / 4
print(directions)

[[[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 ...

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]]


In [93]:
# check the trained model
generator = model.GeneratorNet()
checkpoint = torch.load('models/model_gan_2400.pth.tar')
generator.state_dict(checkpoint['gen_state_dict'])
noise = func.get_noise(1000, 8)
output = generator(noise).data.numpy()
directions = np.round(so.slice_direction(output) * 4) / 4
print(directions)

[[[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 ...

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]

 [[0.5]
  [0.5]
  [0.5]
  ...
  [0.5]
  [0.5]
  [0.5]]]


## Nothing changes